### ISSUE TITLE
ModuleNotFoundError: No module named 'binlog2s3.lib'

### ISSUE THREAD

**Issue by walito** [pboros/binlog2s3#1]
Hello, I tried to install the script and I have the next error trying to run it

ModuleNotFoundError: No module named 'binlog2s3.lib'

Steps
- repo clone
- python setup.py install
- binlog2s3 --help
`Traceback (most recent call last):
  File "/usr/local/bin/binlog2s3", line 11, in <module>
    load_entry_point('binlog2s3==1.0', 'console_scripts', 'binlog2s3')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/binlog2s3-1.0-py3.6.egg/binlog2s3/__main__.py", line 3, in <module>
ModuleNotFoundError: No module named 'binlog2s3.lib'`

Tested on python version 3.8.9 and 3.6.8, same issue
Thanks

**Comment by pboros** [comment]
Hey @walito,

The default python gitignore file had lib in it, so this wasn't pushed. I fixed it, get the changes with git pull or reclone and check now. Thanks for trying this, let me know how it goes.

Peter

**Comment by walito** [comment]
Hello @pboros awesome, thanks for your quick reply, I'll check and keep you updated. Thanks again
